type=OLAP
name=ecommerce_bi_olap
driver=mondrian.olap4j.MondrianOlap4jDriver
location=jdbc:mondrian:JdbcDrivers=com.mysql.cj.jdbc.Driver;Jdbc=jdbc:mysql://localhost:3306/ecommerce_bi?useSSL=false&serverTimezone=UTC;JdbcUser=bi_user;JdbcPassword=bi_password;Catalog=${PROJECT_DIR}/olap/ecommerce_catalog.xml;
username=admin
password=admin
security.enabled=false
