type=OLAP
name=ecommerce_bi_olap_postgres
driver=mondrian.olap4j.MondrianOlap4jDriver
location=jdbc:mondrian:JdbcDrivers=org.postgresql.Driver;Jdbc=jdbc:postgresql://localhost:5432/ecommerce_bi;JdbcUser=postgres;JdbcPassword=postgres;Catalog=file:olap/ecommerce_catalog.xml;
username=admin
password=admin
security.enabled=false
